# Generated by Django 2.2.3 on 2019-08-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(choices=[('zabor', 'Забор'), ('trotuarka', 'Тротуарка')], default='trotuarka', help_text='Name of storage', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Zabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('amount', models.IntegerField(help_text='Для заборов и памятников указывается количество изделий. Для плитки - квадратов', null=True, verbose_name='Количество')),
                ('name', models.CharField(max_length=15, verbose_name='Название изделия')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Sklad', to_field='storage')),
            ],
            options={
                'verbose_name': 'Забор',
                'verbose_name_plural': 'Заборы',
            },
        ),
        migrations.CreateModel(
            name='Trotuarka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('amount', models.IntegerField(help_text='Для заборов и памятников указывается количество изделий. Для плитки - квадратов', null=True, verbose_name='Количество')),
                ('name', models.CharField(choices=[('st_gor', 'Старый Город'), ('kirpichik', 'Кирпичик'), ('romb', 'Ромб')], max_length=15, verbose_name='Название изделия')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Sklad', to_field='storage')),
            ],
            options={
                'verbose_name': 'Тротуарная плитка',
                'verbose_name_plural': 'Тротуарная плитка',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesok', models.IntegerField(verbose_name='Песок т.')),
                ('cement', models.IntegerField(verbose_name='Цемент т.')),
                ('scheben', models.IntegerField(verbose_name='Щебень т. ')),
                ('zavoz', models.DateField(blank=True, null=True, verbose_name='Дата завоза')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Sklad')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='ColorAndPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=100)),
                ('amount', models.IntegerField(help_text='Количество квадратов', null=True, verbose_name='Количество')),
                ('color', models.CharField(choices=[('GR', 'Серый'), ('BR', 'Коричневый'), ('YE', 'Жёлтый'), ('OL', 'Оливковый'), ('BL', 'Синий'), ('RED', 'Красный')], default='GR', max_length=15, verbose_name='Цвет')),
                ('trotuarka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad.Trotuarka')),
            ],
            options={
                'verbose_name': 'Цвет/Цена/Количество тротуарной плитки',
                'verbose_name_plural': 'Цвет/Цена/Количество тротуарной плитки',
            },
        ),
    ]
