# Generated by Django 2.2.3 on 2019-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(choices=[('zabor', 'Забор'), ('trotuarka', 'Тротуарка'), ('monuments', 'Памятники')], default='zabor', help_text='Name of storage', max_length=10)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
    ]
