# Generated by Django 2.2.3 on 2019-07-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('name', models.CharField(choices=[('fagot', 'Фагот'), ('krim', 'Крым'), ('but', 'Бут')], max_length=15, verbose_name='Название изделия')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Sklad')),
            ],
            options={
                'verbose_name': 'Забор',
                'verbose_name_plural': 'Заборы',
            },
        ),
        migrations.CreateModel(
            name='Trotuarka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('name', models.CharField(choices=[('st_gor', 'Старый Город'), ('kirpichik', 'Кирпичик'), ('romb', 'Ромб')], max_length=15, verbose_name='Название изделия')),
                ('color', models.CharField(choices=[('GR', 'Серый'), ('BR', 'Коричневый'), ('YE', 'Жёлтый'), ('OL', 'Оливковый'), ('BL', 'Синий'), ('RED', 'Красный')], default='GR', max_length=15, verbose_name='Цвет')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Sklad')),
            ],
            options={
                'verbose_name': 'Тротуарная плитка',
                'verbose_name_plural': 'Тротуарная плитка',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesok', models.IntegerField(verbose_name='Песок т.')),
                ('cement', models.IntegerField(verbose_name='Цемент т.')),
                ('scheben', models.IntegerField(verbose_name='Щебень т.')),
                ('zavoz', models.DateField(blank=True, null=True, verbose_name='Дата завоза')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Sklad')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
