# Generated by Django 2.2.3 on 2019-08-05 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trotuarka',
            name='colorandprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad.ColorAndPrice', verbose_name='Цвет/Цена'),
        ),
        migrations.AlterField(
            model_name='zabor',
            name='colorandprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad.ColorAndPrice', verbose_name='Цвет/Цена'),
        ),
    ]
