# Generated by Django 2.2.3 on 2019-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_auto_20190806_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorandprice',
            name='co',
            field=models.CharField(choices=[('GR', 'Серый'), ('BR', 'Коричневый'), ('YE', 'Жёлтый'), ('OL', 'Оливковый'), ('BL', 'Синий'), ('RED', 'Красный')], default='GR', max_length=100, verbose_name='Цвет'),
        ),
    ]
