# Generated by Django 2.2.3 on 2019-07-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_materials_trotuarka_zabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='storage',
            field=models.CharField(choices=[('zabor', 'Забор'), ('trotuarka', 'Тротуарка')], default='trotuarka', help_text='Name of storage', max_length=10),
        ),
        migrations.AlterField(
            model_name='trotuarka',
            name='amount',
            field=models.IntegerField(help_text='Для заборов и памятников указывается количество изделий.\r\n Для плитки - квадратов', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='zabor',
            name='amount',
            field=models.IntegerField(help_text='Для заборов и памятников указывается количество изделий.\r\n Для плитки - квадратов', verbose_name='Количество'),
        ),
    ]
