# Generated by Django 2.2.3 on 2019-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_auto_20190806_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorandprice',
            name='amount',
            field=models.IntegerField(help_text='Количество квадратов', null=True, verbose_name='Количество'),
        ),
    ]
