# Generated by Django 2.2.3 on 2019-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_colorandprice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trotuarka',
            name='amount',
            field=models.IntegerField(help_text='Для заборов и памятников указывается количество изделий. Для плитки - квадратов', null=True, verbose_name='Количество'),
        ),
        migrations.RemoveField(
            model_name='trotuarka',
            name='colorandprice',
        ),
        migrations.AddField(
            model_name='trotuarka',
            name='colorandprice',
            field=models.ManyToManyField(blank=True, null=True, to='sklad.ColorAndPrice', verbose_name='Цвет/Цена'),
        ),
        migrations.AlterField(
            model_name='trotuarka',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='zabor',
            name='amount',
            field=models.IntegerField(help_text='Для заборов и памятников указывается количество изделий. Для плитки - квадратов', null=True, verbose_name='Количество'),
        ),
        migrations.RemoveField(
            model_name='zabor',
            name='colorandprice',
        ),
        migrations.AddField(
            model_name='zabor',
            name='colorandprice',
            field=models.ManyToManyField(blank=True, null=True, to='sklad.ColorAndPrice', verbose_name='Цвет/Цена'),
        ),
        migrations.AlterField(
            model_name='zabor',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
