# Generated by Django 2.2.3 on 2019-08-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_auto_20190806_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorandprice',
            options={'verbose_name': 'Цвет/Цена/Количество тротуарной плитки', 'verbose_name_plural': 'Цвет/Цена/Количество тротуарной плитки'},
        ),
        migrations.AlterField(
            model_name='trotuarka',
            name='colorandprice',
            field=models.ManyToManyField(blank=True, to='sklad.ColorAndPrice', verbose_name='Цвет/Цена'),
        ),
        migrations.AlterField(
            model_name='zabor',
            name='colorandprice',
            field=models.ManyToManyField(blank=True, to='sklad.ColorAndPrice', verbose_name='Цвет/Цена'),
        ),
    ]
