# Generated by Django 2.2.3 on 2019-08-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0008_auto_20190807_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorandprice',
            old_name='cena',
            new_name='cost',
        ),
    ]
