# Generated by Django 2.2.3 on 2019-08-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0009_auto_20190807_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorandprice',
            name='color',
            field=models.CharField(choices=[('GR', 'Серый'), ('BR', 'Коричневый'), ('YE', 'Жёлтый'), ('OL', 'Оливковый'), ('BL', 'Синий'), ('RED', 'Красный')], default='GR', max_length=15, verbose_name='Цвет'),
        ),
    ]
